name: Super-Linter

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main




permissions:
  contents: read
  statuses: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # ... your other env vars ...
          CREATE_LOG_FILE: true       # <--- Turn this on
          LOG_FILE: linter.log        # <--- Name the file

      # Add this step to upload the log file so you can download it
      - name: Upload Linter Artifact
        if: always()                  # Run this even if linting fails
        uses: actions/upload-artifact@v4
        with:
          name: linter-log
          path: linter.log
