name: Super-Linter

on: push

jobs:
  super-lint:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter/slim@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true

          # 🟦 Enable full error output
          LOG_LEVEL: DEBUG
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
          PRINT_ALPACA: true
